database:
  driverClass: org.postgresql.Driver
  user: lukecoy
  url: jdbc:postgresql:discogs
  password: Mxs013539
  validationQuery: "/* MyService Health Check */ SELECT 1"
  validationQueryTimeout: 3s

server:
  type: simple
  connector:
    type: http
    port: 8080